name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        node-version: [16.x]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
    - run: |
        cd library_front
        npm ci
    - name: Generate front build
    - run: |
        cd library_front
        npm run build --if-present
    - name: Verify front lint
    - run: |
        cd library_front
        npm lint
    - name: Verify front tests
    - run: |
        cd library_front
        npm test
        
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd library_back
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
 
